apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-movies
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: go-movies
  template:
    metadata:
      labels:
        app: go-movies
    spec:
      containers:
      - image: ingomarlos/go-movies:latest
        name: go-movies
        ports:
        - containerPort: 8080
