apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-movies
  namespace: app1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: go-movies
  template:
    metadata:
      labels:
        app: go-movies
    spec:
      containers:
      - name: go-movies
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: go-app
              key: environment
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: go-app
              key: token
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
