apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-movies-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - host: goapp-poc.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: go-movies-service
            port:
              number: 8080
