apiVersion: v1
kind: Service
metadata:
  name: go-movies
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: go-movies
