apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app1
  namespace: argocd
spec: 
  destination: 
    namespace: app1
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: apps/deploy
    repoURL: "https://github.com/ingomarlos/app-deployment.git"
    targetRevision: main
    helm:
      releaseName: go-movies
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
